name: Create pul request
description: Create a pull request

inputs:
  base-branch:
    description: "Base branch"
    required: true
  to-merge-branch:
    description: "Branch to merge"
    required: true
  title:
    description: "Title of the pull request"
    required: true
  body:
    description: "Body of the pull request"
    required: true
  pat:
    description: "Personal access token"
    required: true

runs:
  using: composite
  steps:
    - name: "Create pull request"
      env:
        GH_TOKEN: ${{ inputs.pat }}
      run: gh pr create -B "${{inputs.base-branch}}" -H "${{inputs.to-merge-branch}}" --title "${{inputs.title}}" --body "${{inputs.body}}"
      shell: bash