name: Dockerize
description: Build and push a Docker image

inputs:
  name:
    description: 'Name of the Docker image'
    required: true
  version:
    description: 'Version of the Docker image'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: registry.nathanaudvard.fr
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: registry.nathanaudvard.fr/naudvard/${{ inputs.name }}:${{ inputs.version }}