name: Build and push Java

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Java version
        id: java-version
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: pom.xml
          xpath: /project/properties/java.version

      -  name: Get project name
         id: project-name
         uses: mavrosxristoforos/get-xml-info@2.0
         with:
           xml-file: pom.xml
           xpath: /project/artifactId

      - name: Build Kotlin
        uses: naudvard/my-actions/.github/actions/build/java@main
        with:
          java-version: ${{ steps.java-version.outputs.info }}
          file-name: ${{ steps.project-name.outputs.info }}

      - name: Dockerize
        uses: naudvard/my-actions/.github/actions/dockerize@main
        with:
          name: ${{ steps.project-name.outputs.info }}
          version: ${{ steps.java-version.outputs.info }}