name: Sync repositories

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: naudvard/my-actions/.github/actions/action-setup-git@fix/sync

      - name: Sync
        uses: naudvard/my-actions/.github/actions/action-sync-repositories@fix/sync
        with:
          source: "my-actions"
          json: "utils/sync-repos.json"
          pat: ${{ secrets.PAT }}
